EASY-2403: Proposal for Change: adding complex elements
DANS-KNAW/easy-update-metadata-dataset pull request #19
Opened 2020-01-20 12:09 UTC by lindareijnhoudt

fixes EASY-2403

#### When applied it will
* add proposal to README for additional functionality to be able to add complex elements to a datastream instead of a simple update

#### Where should the reviewer @DANS-KNAW/easy start?

2020-01-21 16:08 UTC, janvanmansum requested changes
* See my change suggestions for formatting and semantic Markdown improvements.
* The purpose of `additional_directory` is not very well explained. What I understand from the last example is that it contains complex values. If that is the purpose, a better name would be something like `complex-values-directory`. The explanation should not be in an example, but in the command line argument help. The examples should be as literal as possible, i.e. not contain things like `easy-update-metadata-dataset [--doUpdate] <datasets.csv> [additional_directory]` which contain placeholders and optionality-brackets and therefore are too abstract for an example.

2020-01-21 16:08 UTC, janvanmansum commented on README.md
> +    easy-update-metadata-dataset [--doUpdate] <datasets.csv> [additional_directory]
```suggestion
    easy-update-metadata-dataset [--doUpdate] <datasets.csv> [<additional_directory>]
```

2020-01-21 16:08 UTC, janvanmansum commented on README.md
> +**Example: update simple value in EMD**
```suggestion
### Example: update simple value in EMD
```

2020-01-21 16:08 UTC, janvanmansum commented on README.md
> +**Example: update datasetState in AMD**
```suggestion
### Example: update datasetState in AMD
```

2020-01-21 16:08 UTC, janvanmansum commented on README.md
> +**Example: Adding complex content**
```suggestion
### Example: Adding complex content
```

2020-01-21 16:08 UTC, janvanmansum commented on README.md
> +```$csv
I think the dollar sign [should not be there](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting).

2020-01-23 15:12 UTC, jo-pol commented on README.md
> +    easy-update-metadata-dataset [--doUpdate] <datasets.csv> [additional_directory]
I see it is a proposal but wonder why the standard unit test for the readme check is not failing.

2020-02-05 14:21 UTC, janvanmansum requested changes
A few minor things. See my suggested changes. Otherwise OK.

2020-02-05 14:21 UTC, janvanmansum commented on README.md
> +when the `OLD_VALUE` is`NILL`, the value in `NEW_VALUE` must be __added__ to the tag
```suggestion
when the `OLD_VALUE` is`NIL`, the value in `NEW_VALUE` must be __added__ to the tag 
```

https://dictionary.cambridge.org/dictionary/english/nil

2020-02-05 14:21 UTC, janvanmansum commented on README.md
> +###Example: update simple value in EMD
```suggestion
### Example: update simple value in EMD
```
Without the space it doesn't render as a heading on GitHub. You can try this out with the "Display the rich diff" button in the PR.

2020-02-05 14:21 UTC, janvanmansum commented on README.md
> +###Example: check update datasetState in AMD
```suggestion
### Example: check update datasetState in AMD
```

2020-02-05 14:21 UTC, janvanmansum commented on README.md
> +###Example: Adding complex content
```suggestion
### Example: Adding complex content
```

2020-02-05 15:13 UTC, rvanheest commented on README.md
> +easy-dataset:1, EMD,       accessRights, GROUP_ACCESS, OPEN_ACCESS
As this should also be changed in the `DC` stream, please add the extra row for that as well. Not only as an example, but also as a reminder to the one who is seeking to use this tool for updating dataset metadata in Fedora.

2020-02-05 15:14 UTC, rvanheest commented on README.md
> +when the `OLD_VALUE` is`NILL`, the value in `NEW_VALUE` must be __added__ to the tag
following the change by @janvanmansum, but also adding a space:

```suggestion
when the `OLD_VALUE` is `NIL`, the value in `NEW_VALUE` must be __added__ to the tag 
```

2020-02-05 15:16 UTC, rvanheest commented on README.md
> +when the `OLD_VALUE` is`NILL`, the value in `NEW_VALUE` must be __added__ to the tag
Can this (new) `NIL` feature also be used apart from the `complex-values-directory`? If so, please make it a separate example.

2020-02-05 15:18 UTC, rvanheest commented on README.md
> +as a relative path in this directory, referencing a file containing the new value in ~/contributorSnippets/contributor_1.xml
Please add an example of what `contributor_1.xml` would look like.

2020-02-05 15:19 UTC, rvanheest commented on src/main/scala/nl.knaw.dans.easy.umd/CommandLineOptions.scala
>    validateFileIsFile(inputFile)
```suggestion
  validateFileIsFile(inputFile)
  
  validateFileExists(complex_values_directory)
  validateFileIsDirectory(complex_values_directory)
```

2020-02-05 15:21 UTC, rvanheest reviewed
Clever solution! I'd like to see some more improvements on the examples, but apart from that, this looks like a great proposal!

2020-02-06 11:56 UTC, lindareijnhoudt commented on README.md
> +when the `OLD_VALUE` is`NIL`, the value in `NEW_VALUE` must be __added__ to the tag
```suggestion
when the `OLD_VALUE` is `NIL`, the value in `NEW_VALUE` must be __added__ to the tag 
```

2020-02-06 11:59 UTC, janvanmansum approved these changes

2020-02-06 11:59 UTC, janvanmansum approved these changes

2020-02-06 12:00 UTC, lindareijnhoudt commented on README.md
> +easy-dataset:1, EMD,       accessRights, GROUP_ACCESS, OPEN_ACCESS
```suggestion
easy-dataset:1, EMD,       accessRights, GROUP_ACCESS, OPEN_ACCESS
easy-dataset:1, DC,         rights,              GROUP_ACCESS, OPEN_ACCESS
```

2020-02-06 12:12 UTC, lindareijnhoudt commented on README.md
```suggestion
The content of which is 
```xml
<eas:contributor>
    <eas:organization>EU</eas:organization>
    <eas:organizationId eas:identification-system="http://isni.org/" eas:scheme="ISNI">0000 0001 2170 6158</eas:organizationId>
    <eas:role eas:scheme="DATACITE">RightsHolder</eas:role>
</eas:contributor>
```
```

2020-02-06 12:18 UTC, merged