EASY-1007/1003 datasetState in AMD / dcRights in DC
DANS-KNAW/easy-update-metadata-dataset pull request #5
Opened 2016-12-09 15:13 UTC by jo-pol

fixes EASY-1007 + EASY-1003

#### When applied it will

* [x] add history when `datasetState` in `AMD` is changed
* [ ] need both old and new value in input file to prevent changing all `rights` items in the `DC` stream
* 

#### Where should the reviewer @DANS-KNAW/easy start?

The new introduction in the readme.
* The transformation is isolated in an object of its own with new unit tests.
* New warnings on missing types are fixed.

#### How should this be manually tested?

Build, deploy and run as instructed by the readme.

#### related pull requests on github
repo                       | PR
-------------------------- | -----------------
easy-                      | [PR#](PRlink)

2016-12-09 15:54 UTC, jo-pol commented on src/main/scala/nl/knaw/dans/easy/umd/Transformer.scala
> +          Elem(prefix, "lastStateChange", attribs, scope, false, Text(DateTime.now().toString))
I suppose this toString causes one of the compiler warnings.

2016-12-09 17:02 UTC, jo-pol commented on src/main/scala/nl/knaw/dans/easy/umd/Transformer.scala
> +          Elem(prefix, "lastStateChange", attribs, scope, false, Text(DateTime.now().toString))
Seem to need an explicit time zone to for platform independency and fix the travis build.

2016-12-09 21:13 UTC, jo-pol commented on src/main/scala/nl/knaw/dans/easy/umd/CommandLineOptions.scala
>    editBuilder(_.setHelpWidth(110))
he;[width 6 characters too wide for an iPad

2016-12-09 21:37 UTC, jo-pol commented on src/main/scala/nl/knaw/dans/easy/umd/Command.scala
> +  } yield records.size
In test mode you might not (always) want to fail fast when the transformations detect problems with the content of a stream of a particular dataset.

2016-12-13 18:17 UTC, jo-pol commented
Not yet tested from the command line but otherwise ready for review.

2016-12-15 08:31 UTC, jo-pol commented on src/main/scala/nl/knaw/dans/easy/umd/Command.scala
>        case Success((count)) => log.info(s"Changed $count ${ps.streamID} streams.")
The count of updated records is not properly logged.

2016-12-16 09:24 UTC, jo-pol commented
So far we designed the application to have the stream-id and xml-tag to be changed on the command line and the dataset id and old/new values in the csv. Perhaps it is better to have the stream-id and tag in the csv too. 

The change would allow to change EMD and DC in one batch. Now we are forced to work with different batches and when one of them halfway runs into trouble we have a whole bunch of datasets with EMD not matching DC. Within a single batch we can reduce the inconsistent state to a single dataset.

The easiest solution to implement would be a format like:

    FEDORA_ID,STREAM_ID,XML_TAG,NEW_VALUE,OLD_VALUE
    easy-dataset:998,EMD,accessRights,GROUP_ACCESS,OPEN_ACCESS
    easy-dataset:998,DC,rights,GROUP_ACCESS,OPEN_ACCESS
    easy-dataset:999,EMD,accessRights,GROUP_ACCESS,OPEN_ACCESS
    easy-dataset:999,DC,rights,GROUP_ACCESS,OPEN_ACCESS

A more user friendly format would be to allow to repeat the columns STREAM_ID,XML_TAG,NEW_VALUE,OLD_VALUE

The second format would allow (but doesn't necessarily needs to) to reduce the risk of an inconsistent state to a broken connection between updating the streams for one dataset. This potential additional safety leads to questions about error handling options, such as: should we only update if all streams/tags are actually changed or should we abort when just some of the streams/tags are changed.

2016-12-21 09:01 UTC, janvanmansum commented
@jo-pol : please, run the build before you mark your PR as ready for merging.

2016-12-23 13:41 UTC, janvanmansum commented on src/main/scala/nl/knaw/dans/easy/umd/Transformer.scala
> +          Elem(prefix, "lastStateChange", attribs, scope, false, Text(DateTime.now().toString))
@jo-pol:
The warnings are caused by a missing dependency. I have solved this before for `easy-stage-dataset` and other projects by just adding the dependency (even though it is apparently not used at runtime). See this fragment from `easy-staged-dataset`'s `pom.xml`:
```xml
        <dependency>
            <!-- Necessary to get rid of jodatime warnings about missing FromString
                (Jodatime is a transitive dependency through yourmediashelf)  -->
            <groupId>org.joda</groupId>
            <artifactId>joda-convert</artifactId>
        </dependency>
```

Please, apply this solution to your PR, so I can merge it.

2016-12-23 13:41 UTC, janvanmansum requested changes
See my comment about the build warnings.

2016-12-23 15:34 UTC, janvanmansum requested changes
I am getting the following error:
```
16:27:25.261 [main] ERROR nl.knaw.dans.easy.umd.Command$ - Failed Parameters(false,fedoraURL=http://localhost:8080/fedora, user=fedoraAdmin,/vagrant/shared/deasy-input.csv)
java.lang.Exception: failed to process: InputRecord(5,easy-dataset:4,EMD,datasetState,HISTORY,ANY_DISCIPLINE), reason: could not find EMD <HISTORY>HISTORY</HISTORY>```

2017-01-19 11:46 UTC, jo-pol commented
I see only a MaxPermSize warning in the travis build and the other change request is addressed in https://github.com/DANS-KNAW/easy-update-metadata-dataset/pull/5/commits/8d7b5c82d58455972bf646ad77dc36a211d882ad

2017-01-23 11:03 UTC, merged